# Generated by Django 3.1 on 2020-08-19 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='date',
            new_name='created_at',
        ),
    ]
